input-output-hk/metronome

README.md, build.sc, metronome/rocksdb/src/io/iohk/metronome/rocksdb/RocksDBStore.scala, metronome/rocksdb/test/src/io/iohk/metronome/rocksdb/RocksDBStoreSpec.scala, metronome/storage/src/io/iohk/metronome/storage/KVCollection.scala, metronome/storage/src/io/iohk/metronome/storage/KVStore.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreOp.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreRead.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreState.scala, metronome/storage/src/io/iohk/metronome/storage/package.scala, metronome/storage/test/src/io/iohk/metronome/storage/KVStoreStateSpec.scala
Adds a `KVStore` abstraction using a `Free` monad so that we can execute queries/writes against multiple data stores in one batch, including in a transaction if we upgrade to the next version of RocksDB.
Includes an in-memory implementation as well, against which the RocksDB one is tested.
Check out `KVStoreStateSpec` for to have an idea how this could be used. Each domain object is in a separate collection like we have them in Mantis (e.g. `BlockStore`, `BlockHeaderStore`, `AppStateStore`), each with its own key and value type. 
The idea is that normal code would compose queries such as this:
```scala
val query: KVStore[Namespace, Boolean] = for {
bestBlockNumber <- AppStateStore.getBestBlockNumber
bestBlockHash <- BlockNumberMapping.get(bestBlockNumber)
nextBlockNumber = …
```
=> PM-2903: Storage and RocksDB interface

.circleci/config.yml, .circleci/publish.sh
Copied the publish script from Scalanet. Using `sudo` because we're using the `circleci` version of the JDK docker image. The one that isn't from `circleci` would have no support for `BASH_ENV` so the way Coursier is installed wouldn't work any more.
=> PM-3093: Add publish script.

build.sc, metronome/logging/src/io/iohk/metronome/logging/HybridLog.scala, metronome/logging/src/io/iohk/metronome/logging/HybridLogObject.scala, metronome/logging/src/io/iohk/metronome/logging/InMemoryLogTracer.scala, metronome/logging/src/io/iohk/metronome/logging/LogTracer.scala, metronome/networking/src/io/iohk/metronome/networking/ConnectionHandler.scala, metronome/networking/src/io/iohk/metronome/networking/NetworkEvent.scala, metronome/networking/src/io/iohk/metronome/networking/NetworkTracers.scala, metronome/networking/src/io/iohk/metronome/networking/RemoteConnectionManager.scala, metronome/networking/test/resources/logback.xml, metronome/networking/test/src/io/iohk/metronome/networking/ConnectionHandlerSpec.scala, metronome/networking/test/src/io/iohk/metronome/networking/RemoteConnectionManagerWithMockProviderSpec.scala, metronome/networking/test/src/io/iohk/metronome/networking/RemoteConnectionManagerWithScalanetProviderSpec.scala, metronome/tracing/src/main/scala/io/iohk/metronome/tracer/Tracer.scala
Adds structured logging to capture some network events via tracing. The logs are only demonstrated in the tests (and only visible if the log level in `networking/test/resources/logback.xml` is adjusted from `ERROR` to `DEBUG`).
Adopted a [hybrid log format](https://medium.com/unomaly/logging-wisdom-how-to-log-5a19145e35ec) consisting of a human readable `message` and key-value pairs in the form of a JSON object in `event`.
The resulting logs look like this:
```
21:25:44.871 DEBUG i.i.m.networking.NetworkEvent ConnectionFailed {"key":"1bc14e1ac7f929c83b05d796a591c272e36ab7a6e71df41c330c1e21d377af6d300cb73a9395da68708fc2d05c0cd1800b4d07dcf88940f05b161277da4926cd","address":"localhost/127.0.0.1:45765","err":"Error establishing channel to PeerInfo(BitVector(512 bits, …
```
=> PM-2907: Emit trace events from networking.

metronome/networking/src/io/iohk/metronome/networking/ConnectionHandler.scala, metronome/networking/src/io/iohk/metronome/networking/ConnectionsRegister.scala, metronome/networking/src/io/iohk/metronome/networking/RemoteConnectionManager.scala, metronome/networking/test/src/io/iohk/metronome/networking/ConnectionHandlerSpec.scala, metronome/networking/test/src/io/iohk/metronome/networking/MockEncryptedConnectionProvider.scala, metronome/networking/test/src/io/iohk/metronome/networking/RemoteConnectionManagerWithMockProviderSpec.scala
Add possibility to safely replace conflicting connections. Main use case for this feature is the case when, node is restarted after failure and what to reconnect to members in cluster who are not aware of it.
Main things done here:
- add more context info to `HandledConnection` which is now totally internal to `ConnectionHandler`
- different logic for handling conflicts in case of incoming and outgoing connections.
=> [PM-3092] Replace duplicated connections

metronome/checkpointing/interpreter/src/io/iohk/metronome/checkpointing/interpreter/models/Transaction.scala
Adds the most minimalistic `Transaction` type I can think of. 
I think these can become part of the ledger as-is. 
So far we haven't discovered a need for the service to know the `height` of the proposer blocks and the checkpoint candidate. I thought this could be relevant during the update of the ledger: say we have to checkpoint every 10th height in the chain, there's no checkpoint yet for height 100, and we have these events:
1. Alice adds a proposer block transaction for level 101
1. Bob adds a checkpoint candidate for level 100 - it probably cannot enforce the inclusion of Alice's proposer at level 101
1. The ledger is updated, the accumulated proposer blocks are discarded, the new checkpoint is the one sent by Bob - should we keep Alice's proposer block in the ledger?
During our …
=> PM-2929: Transaction data structure.

metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/models/Block.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/models/Ledger.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/models/RLPCodecs.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/models/RLPHash.scala, metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/models/ArbitraryInstances.scala, metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/models/RLPCodecsProps.scala, metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/models/RLPCodecsSpec.scala
Creates a `Block` data structure with a `Block.Header` and `Block.Body` part. I thought it would have actually eliminated some possible hash mismatches if the header and body wasn't separated, but in the concept document the working theory was that the Checkpoint Certificate will have a list of block headers in it, so I stick to it. I guess it's conventional as well to separate the two.
Introduced separate `Hash` types for each of `Header`, `Body` and `Ledger`. 
__Questions__
Do we want to add more fields to the `Block.Header`?
* `height`: When someone proposes a block to us, and we miss its parent, we could look at the last block we have a cetificate for and ask for a whole range of blocks, rather than one by one, following parent-child relationships. It could also help with pruning old …
=> PM-2930: Block data structure

build.sc, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/CheckpointingAgreement.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Block.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/CheckpointCertificate.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Ledger.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/MerkleTree.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/RLPCodecs.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/RLPHash.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Transaction.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/package.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/ArbitraryInstances.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/LedgerProps.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/RLPCodecsProps.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/RLPCodecsSpec.scala, metronome/networking/test/src/io/iohk/metronome/networking/RemoteConnectionManagerWithScalanetProviderSpec.scala
Adds the `CheckpointCertificate` type along with a `MerkleTree` component to hold the types for a Merkle root hash and a Merkle proof. Hashing/proving is not implemented in this PR.
Just realised that the certificate is supposed to contain block headers, so all models need to be visible to the interpreter, so I added a `checkpointing.models` module to hold everything together, referenced by both `checkpointing.service` and `checkpointing.interpreter`.
Also added a module reference to the `hotstuff.consensus` to be able to use the `QuorumCertificate` in the checkpoint.
=> PM-2932: Checkpoint certificate data structure

build.sc, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Block.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/BlockStorage.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/BlockStorageProps.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreRead.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreState.scala
Created a `BlockStorage` component under `hotstuff.service` that stores anything that has a `hotstuff.consensus.basic.Block` type class. The component manages parent-child relationships and makes available some traversal methods that were useful in tentative branch management. 
Also supports a pruning method which can be used to get rid of any block that isn't a descendant of a given hash. This can be used for example to periodically walk up the main chain from the last committed block, and get rid of anything that isn't a descendant of a block that is the, say, the 100th ancestor of the last committed block:
```scala
def prune[F[_]: Sync](
db: RocksDBStore[F], 
blockStorage: BlockStorage[RocksDB.Namespace, CheckpointingAggreement], 
commitQC: QuorumCertificate[CheckpointingAgreement], …
```
=> PM-3104: Generic BlockStorage component for HotStuff

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ConsensusService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/HotStuffService.scala
Updates the view state after handling state transitions if changes are detected.
Opened against `feat-sync` which has all previous PRs merged: https://github.com/input-output-hk/metronome/pull/25, https://github.com/input-output-hk/metronome/pull/28 and https://github.com/input-output-hk/metronome/pull/31
=> PM-3112: Update view state

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/BlockStorage.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/BlockStorageProps.scala, metronome/storage/src/io/iohk/metronome/storage/KVCollection.scala, metronome/storage/src/io/iohk/metronome/storage/KVStore.scala
Changes the `BlockStore` in anticipation of block synchronisation to be able to insert blocks in reverse, or any other order, and still maintain parent-child relationships. 
Currently if a child is inserted before its parent, then the parent-to-children association will not be populated, and traversal from ancestors towards descendants will not work. After the change, the parent-to-children association is established by the insertion of the children. The removal happens when the last child _and_ the parent are all removed. 
Added a `KVStore.alter` method (like `Data.Map.alter` in Haskell) to be able to insert/update/delete in one operation.
I expect that during block synchronisation we'll start walking the tree backwards until one of these conditions hold:
* we find a block we already …
=> PM-3104: Insert blocks in any order

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ConsensusService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/HotStuffService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/ViewStateStorage.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/ViewStateStorageProps.scala, metronome/rocksdb/src/io/iohk/metronome/rocksdb/RocksDBStore.scala, metronome/storage/src/io/iohk/metronome/storage/KVStore.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreOp.scala, metronome/storage/src/io/iohk/metronome/storage/KVStoreRead.scala
Adds a `ViewStateStorage` component to store pieces of the `ProtocolState` that should survive a restart. These are the view number, the prepare/locked/commit Q.C., and the last executed block. At least I couldn't think of anything else now. (Actually there's one more thing: the root of the block tree, but I'll add that in the block synchronisation story; it will be used for pruning blocks when we can skip ahead to a new committed state without syncing blocks in between. EDIT: Added in https://github.com/input-output-hk/metronome/pull/37).
The storage is initialised by the genesis data, so it always has something to return. All items are stored under different keys, because they change at different points in time, and this way we don't have to retrieve some data, update it, then save it …
=> PM-3112: ViewState persistence

build.sc, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/storage/LedgerStorage.scala, metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/storage/LedgerStorageProps.scala, metronome/storage/src/io/iohk/metronome/storage/KVRingBuffer.scala
Adds a `LedgerStorage` component that stores a certain number of the latest ledger instances in a ring buffer. The idea is that we only need to keep the last committed state, however we want to leave some time for other nodes that may need to sync with us to request it, so we can configure a lag after which the oldest ledger is overwritten. 
It is located in `checkpointing.service.storages` so it doesn't have to deal with anything generic, we know the ledger is going to be small. 
Builds on https://github.com/input-output-hk/metronome/pull/31 so keys don't need `Codec` just `Encoder`.
=> PM-3105: Ledger persistence

metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/CheckpointingAgreement.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Block.scala, metronome/core/src/io/iohk/metronome/core/Pipe.scala, metronome/core/src/io/iohk/metronome/core/fibers/DeferredTask.scala, metronome/core/src/io/iohk/metronome/core/fibers/FiberMap.scala, metronome/core/src/io/iohk/metronome/core/fibers/FiberSet.scala, metronome/core/src/io/iohk/metronome/core/messages/RPCMessage.scala, metronome/core/src/io/iohk/metronome/core/messages/RPCTracker.scala, metronome/core/test/src/io/iohk/metronome/core/fibers/FiberMapSpec.scala, metronome/core/test/src/io/iohk/metronome/core/fibers/FiberSetSpec.scala, metronome/core/test/src/io/iohk/metronome/core/messages/RPCTrackerSpec.scala, metronome/hotstuff/consensus/src/io/iohk/metronome/hotstuff/consensus/basic/Block.scala, metronome/hotstuff/consensus/test/src/io/iohk/metronome/hotstuff/consensus/basic/HotStuffProtocolProps.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ConsensusService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/HotStuffService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/SyncService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/messages/SyncMessage.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/BlockStorage.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/sync/BlockSynchronizer.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/SyncEvent.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/SyncTracers.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/BlockStorageProps.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/ViewStateStorageProps.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/sync/BlockSynchronizerProps.scala, metronome/storage/src/io/iohk/metronome/storage/InMemoryKVStore.scala
Required PRs are https://github.com/input-output-hk/metronome/pull/29, https://github.com/input-output-hk/metronome/pull/28, https://github.com/input-output-hk/metronome/pull/25 and https://github.com/input-output-hk/metronome/pull/31
* Added an `RPCTracker` component that can match (optional) responses to requests, or issue a timeout.
* Added `BlockSynchronizer` to download and persist blocks that have a Quorum Certificate.
* Wired together `SyncService` and `BlockSynchronizer`. 
* Enhanced `FiberMap` with the ability the cancel the enqueued tasks of a key.
The idea is that we have a block tree in persistent storage, but sometimes a `Prepare` message can contain a block we don't have a parent for. But the `Prepare` message contains the Quorum Certificate for that parent, so we know that …
=> PM-3134: Block synchronisation

build.sc, metronome/hotstuff/consensus/src/io/iohk/metronome/hotstuff/consensus/Federation.scala, metronome/hotstuff/consensus/src/io/iohk/metronome/hotstuff/consensus/ViewNumber.scala, metronome/hotstuff/consensus/test/src/io/iohk/metronome/hotstuff/consensus/basic/ProtocolStateProps.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/Status.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/SyncService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/sync/ViewSynchronizer.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/SyncEvent.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/SyncTracers.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/sync/ViewSynchronizerProps.scala
Added a ViewSynchronizer component that asks all federation members for their current Status and determines the best values to adopt: it picks the highest Prepare and Commit Quorum Certificates, and the median View Number. The former have signatures to prove their validity, but the latter could be gamed by adversarial actors, hence not using the highest value. Multiple rounds of peers trying to sync with each other and picking the median should make them converge in the end.
The integration with the services is in https://github.com/input-output-hk/metronome/pull/37
=> PM-3063: View synchronisation (Part 1)

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ConsensusService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/HotStuffService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/SyncService.scala, metronome/networking/src/io/iohk/metronome/networking/Network.scala, metronome/networking/test/src/io/iohk/metronome/networking/NetworkSpec.scala
Just moves the `Network` trait to `networking` and makes it more generic, decoupled from `Agreement`.
=> PM-3146: Move Network to networking.

metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/storage/LedgerStorageProps.scala, metronome/rocksdb/src/io/iohk/metronome/rocksdb/RocksDBStore.scala
Discovered as part of testing https://github.com/input-output-hk/metronome/pull/42
I should not have missed this: when using `Task`, multiple operations are executed synchronously in `flatMap` (unlike with `Future` which does everything asynchronously) until the thread yields and processes other tasks. The way locking and unlocking was done was susceptible to the lock being taken on one thread and the unlock attempted on another, resulting in rather elusive deadlocks. In the end I saw `RocksDBStore` mentioned in thread dumps, with threads waiting on read and write locks, and it turned out sometimes it cannot unlock. 
Changed the database to use the `Eval` monad in compiling the `Free` operations, and only at the edge turn them into `F[A]`.
=> PM-3241: Fix RocksDB locking to be synchronous.

metronome/networking/src/io/iohk/metronome/networking/LocalConnectionManager.scala, metronome/networking/src/io/iohk/metronome/networking/RemoteConnectionManager.scala
Adds a `LocalConnectionManager` to the `networking` package that we can use to connect to a single address. It reuses the `RemoteConnectionManager` which already takes care of reconnections, and manages the connections whichever side initiated them first. 
The idea is that instead of the Checkpointing Service acting as a client and the PoW interpreter acting as a server, they can both try to connect to each other, and keep reconnecting if the other side disappears for a while. It would be enough if one side does it (the Service probably being a better candidate) but this way we should be able to reuse all our existing code, and if the Checkpointing Service is down, we should see some warnings on the Interpreter side as well.
=> PM-3129: Add LocalConnectionManager on top of the remote one.

build.sc, metronome/networking/src/io/iohk/metronome/networking/ConnectionHandler.scala, metronome/networking/src/io/iohk/metronome/networking/EncryptedConnectionProvider.scala, metronome/networking/src/io/iohk/metronome/networking/NetworkEvent.scala, metronome/networking/src/io/iohk/metronome/networking/NetworkTracers.scala, metronome/networking/src/io/iohk/metronome/networking/RemoteConnectionManager.scala, metronome/networking/src/io/iohk/metronome/networking/ScalanetConnectionProvider.scala, metronome/networking/test/src/io/iohk/metronome/networking/ConnectionHandlerSpec.scala, metronome/networking/test/src/io/iohk/metronome/networking/MockEncryptedConnectionProvider.scala, metronome/networking/test/src/io/iohk/metronome/networking/RemoteConnectionManagerWithMockProviderSpec.scala
The integration tests of https://github.com/input-output-hk/metronome/pull/51 failed with often with this kind of network log:
```
localhost/127.0.0.1:34953 - 2021-06-04T16:43:30.044162Z: ConnectionRegistered(Peer(ECPublicKey(ByteVector(64 bytes, 0x697fa1a96f44dd9e...)),localhost/127.0.0.1:37597))
localhost/127.0.0.1:37597 - 2021-06-04T16:43:30.050472Z: ConnectionRegistered(Peer(ECPublicKey(ByteVector(64 bytes, 0x7c308620b5c8d000...)),localhost/127.0.0.1:34953))
localhost/127.0.0.1:37597 - 2021-06-04T16:43:30.082489Z: ConnectionDiscarded(Peer(ECPublicKey(ByteVector(64 bytes, 0x7c308620b5c8d000f...)),localhost/127.0.0.1:34953))
localhost/127.0.0.1:37597 - 2021-06-04T16:43:30.127455Z: ConnectionDeregistered(Peer(ECPublicKey(ByteVector(64 bytes, …
```
=> PM-3092: Connection conflict resolution based on ephemeral port ordering

build.sc, metronome/config/src/io/iohk/metronome/config/ConfigDecoders.scala, metronome/config/src/io/iohk/metronome/config/ConfigParser.scala, metronome/config/test/resources/complex.conf, metronome/config/test/resources/override.conf, metronome/config/test/resources/simple.conf, metronome/config/test/src/io/iohk/metronome/config/ConfigParserSpec.scala
Created a `config` module that can be used to parse HOCON config into case classes in a single step, allowing overrides from env vars. 
One problem with how we tend to use TypeSafe config is to have a method like `MyConfig.fromConfig(root.getConfig("path.to.my.config")`, which typically returns a `MyConfig` instance, or throws an error if there's a problem with the values. The other is that we can't say when this happens, as these configuration values are sometimes accessed lazily. 
The approach here does all parsing up front, so we can get all potential problems out of the way at program startup. It may be less convenient in that it's not easy to make decisions based on the values, unless some complex parser is written. A simple case of switching between identical alternatives is encoded …
=> PM-2941: Config parser

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ApplicationService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/ConsensusService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/HotStuffService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/SyncService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/execution/BlockExecutor.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/BlockStorage.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/ViewStateStorage.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/ConsensusEvent.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/tracing/ConsensusTracers.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/execution/BlockExecutorProps.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/BlockStorageProps.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/sync/ViewSynchronizerProps.scala
Added a `BlockExecutor` component to farm out the `ExecuteBlocks` effects from the `ConsensusService`. It has an internal work queue where batches are added. A successful execution is noted down in the `ViewStateStorage`. The actual execution is delegated to the `ApplicationService`. If there's an error, we try again next time there's a new batch.
If the `ConsensusService` and the `SyncService` skip ahead to a newer Commit Quroum Certificate, and the last executed block is no longer available, the `BlockExecutor` skips blocks too. Not much else it can do. These events are traced.
=> PM-3133: Block executor

metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/storage/BlockStorage.scala, metronome/hotstuff/service/test/src/io/iohk/metronome/hotstuff/service/storage/BlockStorageProps.scala, metronome/storage/src/io/iohk/metronome/storage/KVRingBuffer.scala, metronome/storage/src/io/iohk/metronome/storage/KVTree.scala
Extracted all the generic logic from `BlockStorage` into a `KVTree` component that the former now inherits. Testing is still through `BlockStorageProps` - I would have to test with some test data anyway, it's just in a different module.
This could facilitate storing things that follow the block tree structure (such as the tentative ledger) and reuse methods like pruning.
Builds on https://github.com/input-output-hk/metronome/pull/55 because the `height` is needed to avoid unnecessary traversals for ancestors now.
=> PM-3419: Generalise BlockStorage into KVTree

build.sc, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/Ledger.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/ArbitraryInstances.scala, metronome/checkpointing/models/test/src/io/iohk/metronome/checkpointing/models/LedgerProps.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/CheckpointingService.scala, metronome/checkpointing/service/test/src/io/iohk/metronome/checkpointing/service/CheckpointingServiceProps.scala
The motivation is that since in the normal flow a block is first validated and the resulting state is saved in memory then it should not be necessary for `BlockExecutor` to prepare a batch of blocks to execute. The chosen design however should work with or without it. Having the intermediate Ledgers saved in memory should not require any additional queries to the persistent storage during execution, as long as the service run uninterrupted.
The in memory map of Ledgers should always hold the last committed state, being reset to that single value after each commit. The associated block headers can be used to construct the checkpoint certificate.
=> [PM-3108] Update Ledger

metronome/config/src/io/iohk/metronome/config/ConfigDecoders.scala, metronome/config/test/resources/complex.conf, metronome/config/test/src/io/iohk/metronome/config/ConfigParserSpec.scala
Overrides from `-D` system properties turned Boolean values into String.
Thanks to @biandratti for noticing and the fix.
=> FIX: Add ConfigDecoders.booleanDecoder 

metronome/checkpointing/models/props/src/io/iohk/metronome/checkpointing/models/CheckpointCertificateProps.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/CheckpointCertificate.scala, metronome/checkpointing/models/src/io/iohk/metronome/checkpointing/models/MerkleTree.scala
Add `CheckpointCertificate.validate` so that the Interpreter implementations can rely on a function provided by the library to verify the contents.
=> PM-3562: Validate a checkpointing certificate.

build.sc, metronome/checkpointing/service/props/src/io/iohk/metronome/checkpointing/service/BlockCreationProps.scala, metronome/checkpointing/service/props/src/io/iohk/metronome/checkpointing/service/CheckpointingServiceFixtures.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/CheckpointingService.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/InterpreterClient.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/messages/CheckpointingMessage.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/tracing/CheckpointingEvent.scala, metronome/core/src/io/iohk/metronome/core/messages/RPCSupport.scala, metronome/examples/src/io/iohk/metronome/examples/robot/service/RobotService.scala, metronome/hotstuff/service/src/io/iohk/metronome/hotstuff/service/SyncService.scala
Adds the boilerplate-y machinery to the `CheckpointingService` to:
* handle `GetStateRequest` and `GetStateResponse` in the `CheckpointinService` 
* implement the `syncState` logic
These are both like-for-like copies from the `RobotService`. Some of the request/response handling has been pulled out from all the classes that had them (`SyncService`, `RobotService`, `InterpreterClient`) so they could be reused in the `CheckpointingService`. I also separated the network message handling into a private class to limit the size of the service and the scope that has to be understood. 
Added tracing as well for the most significant events.
The PR doesn't contain any tests. They'd be rather tedious to write, and I'd rather implement https://jira.iohk.io/browse/PM-3138 in a similar fashion to …
=> PM-3135: Implement state synchronization in the CheckpointingService

build.sc, metronome/config/specs/resources/array.conf, metronome/config/specs/src/io/iohk/metronome/config/ConfigParserSpec.scala, metronome/config/src/io/iohk/metronome/config/ConfigDecoders.scala
System property override like
```
./bin/node -Dblockchain.testnet.bootstrap-nodes.0='enode://asdfasdf'
```
Did not actually override an element, but turned the array into `JsonObject` instead!
```
"bootstrap-nodes":{"0":"enode://asdfasdf"}
```
In order to handle those Seq, List, Vector codec failovers were introduced.
Gaps between keys are **no longer** ignored, so keys like `{1,0,2}` will be accepted and values sorted, but `{3,5,2}` will fail the decoder with a corresponding message
Testcases were provided as well
=> Added failover codecs for json array override support

metronome/checkpointing/interpreter/props/src/io/iohk/metronome/checkpointing/interpreter/messages/ArbitraryInstances.scala, metronome/checkpointing/interpreter/specs/src/io/iohk/metronome/checkpointing/interpreter/InterpreterServiceSpec.scala, metronome/checkpointing/interpreter/src/io/iohk/metronome/checkpointing/interpreter/InterpreterRPC.scala, metronome/checkpointing/interpreter/src/io/iohk/metronome/checkpointing/interpreter/InterpreterService.scala, metronome/checkpointing/interpreter/src/io/iohk/metronome/checkpointing/interpreter/codecs/DefaultInterpreterCodecs.scala, metronome/checkpointing/interpreter/src/io/iohk/metronome/checkpointing/interpreter/messages/InterpreterMessage.scala, metronome/checkpointing/service/props/src/io/iohk/metronome/checkpointing/service/BlockCreationProps.scala, metronome/checkpointing/service/props/src/io/iohk/metronome/checkpointing/service/CheckpointingServiceFixtures.scala, metronome/checkpointing/service/specs/src/io/iohk/metronome/checkpointing/service/InterpreterClientSpec.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/CheckpointingService.scala, metronome/checkpointing/service/src/io/iohk/metronome/checkpointing/service/InterpreterClient.scala
Adds the ability for the Interpreter to signal to the Service that some transactions in the mempool can be unconditionally forgotten.
Normally we'd keep the transactions in the mempool until a block that contains them is executed, however, some transactions may be there that can never be included in a block. Since `CreateBlockBodyRequest` contains the `mempool`, `CreateBlockBodyResponse` can be used to signal that some of the content has been inspected and is no longer interesting.
=> PM-3699: Option to return transactions to be purged during block creation

build.sc
The classes in `metronome-logging` are useful for the wallet backend to implement logging by using contravariant tracers.
This PR should publish `metronome-logging` in our internal repo.
=> [MW-511] Publish metronome-logging to be used by Midnight wallet backend
